name: "Check libc++ generated files"
on:
  pull_request:
    paths:
      - 'libcxx/**'

permissions:
  contents: read

jobs:
  check_generated_files:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: aminya/setup-cpp@28288fd7bc9318eb46da43d2d6b5cf6a4d19ce6d # v1.5.4
        with:
          clangformat: 17.0.1
          ninja: true

      - name: Check generated files
        run: libcxx/utils/ci/run-buildbot check-generated-output
